<?php
/*PLUGINS*/
require_once('plugins/Smtp.php');
require_once('plugins/Facebook.php');
/*CONTROLLERS*/
require_once('controllers/Api.php');
require_once('controllers/Defines.php');
require_once('controllers/Sidebars.php');
require_once('controllers/Email.php');
